### ISSUE TITLE
Villagers are lobotomized in areas they shouldn't be

### ISSUE THREAD

**Issue by PPGOME** [mja00/VillagerLobotimizer#3]
Server version: Paper 1.21.5-69
Plugin version: 1.8.2

Hello,

I've had a number of reports that players' villagers have been getting lobotomized in places they shouldn't be. This includes:

- Inside of doors
- On top of beds
- On top of carpets
- Up against cocoa beans
- Inside of 2-tall hallways

The plugin seems to think the villager is "stuck" when the block at its feet isn't air and also gets confused when there's a block directly above it.

Please let me know if any further information is needed!

**Comment by mja00** [comment]
Yeah there's probably some cases where it'll think its trapped in a 1x1 box. I'll see if I can't tweak the logic.

**Comment by mja00** [comment]
I've fixed all of these, although two of them require config values to be enabled (solely due to the ability of players technically being able to abuse it to disable lobotomization).

In your config you'll want to add:
```yaml
#To ignore villagers stuck in doors, set this to true.
ignore-villagers-stuck-in-doors: true

#To not lobotomize villagers surrounded by non-solid blocks, set this to true.
ignore-non-solid-blocks: true
```

Which'll fix the bug with cocoa pods and doors (essentially they always pass the can walk through check if those configs are enabled). 
Bed, carpet, and 2-tall hallways were due to bad logic. 

I've released a snapshot version on Hangar: https://hangar.papermc.io/mja00/VillagerLobotomy/versions/1.9.0-snapshot-4a1bc00 

If you don't mind trying it out with those configs enabled to see if it fixes the issues for you and if so then I'll release the version fully.
